import {Calc,parseA,A,isErr,cloneValue} from './sheet-engine.js';
const same=(a,b)=>String(a).toLocaleLowerCase()===String(b).toLocaleLowerCase();
const blank=v=>v==null||v==='';
function check(data){if(!Array.isArray(data.columns)||!data.columns.length||new Set(data.columns).size!==data.columns.length||data.columns.some(v=>!String(v).trim())||!Array.isArray(data.rows)||data.rows.some(r=>!Array.isArray(r)||r.length!==data.columns.length))throw Error('查询数据需要非空、不重复的列名，且每行列数一致');if(data.rows.some(r=>r.some(v=>v!=null&&!(typeof v==='string'||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v)))))throw Error('查询单元格必须是文本、有限数字、布尔值或空值');if(data.columns.length>16384||data.rows.length>1048575)throw Error('查询结果超过工作表上限');return data;}
function index(data,name){const i=data.columns.indexOf(name);if(i<0)throw Error('找不到列：'+name);return i;}
function project(data,cols){const ids=cols.map(c=>index(data,c));return check({columns:cols,rows:data.rows.map(r=>ids.map(i=>r[i]))});}
export function importQueryText(text,options={}) {
 if(options.format==='json') {const rows=JSON.parse(text);if(!Array.isArray(rows)||!rows.length)throw Error('JSON 数据必须是非空数组');if(Array.isArray(rows[0]))return check({columns:rows[0].map(String),rows:rows.slice(1).map(r=>r.map(v=>v&&typeof v==='object'?JSON.stringify(v):v))});if(rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw Error('JSON 数据必须全部为对象或全部为数组');const columns=[...new Set(rows.flatMap(r=>Object.keys(r)))];return check({columns,rows:rows.map(r=>columns.map(c=>r[c]&&typeof r[c]==='object'?JSON.stringify(r[c]):r[c]??null))});}
 const sep=options.delimiter??(text.includes('\t')?'\t':','),rows=[];let row=[],value='',quoted=false;
 for(let i=0;i<=text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else if(quoted||!value)quoted=!quoted;else value+=c;}else if(!quoted&&(c===sep||c==='\n'||c==='\r'||c===undefined)){row.push(value);value='';if(c!==sep){if(row.some(v=>v!==''))rows.push(row);row=[];if(c==='\r'&&text[i+1]==='\n')i++;}}else if(c!==undefined)value+=c;}
 if(quoted)throw Error('文本中的引号没有闭合');if(!rows.length)throw Error('文本没有数据');const columns=options.header===false?rows[0].map((_,i)=>'Column'+(i+1)):rows.shift().map(s=>s.replace(/^\uFEFF/,''));return check({columns,rows});
}
export function querySource(doc,source,context) {
 if(source.query)return runQuery(doc,source.query,context);
 if(source.data)return check(cloneValue(source.data));
 let si=doc.sheets.findIndex(s=>same(s.name,source.sheet)),range=source.range;
 if(source.table)doc.sheets.forEach((s,i)=>{const t=s.tables?.find(t=>same(t.name,source.table));if(t){si=i;const [a,b]=t.range.split(':').map(parseA);range=A(a.r,a.c)+':'+A(b.r-(t.totals?1:0),b.c);}});
 if(si<0)throw Error('找不到查询源工作表：'+source.sheet);
 const [a,b0]=String(range||'').split(':').map(parseA),b=b0||a;if(!a||!b||b.r<a.r||b.c<a.c||(b.r-a.r+1)*(b.c-a.c+1)>5000000)throw Error('查询源区域无效或过大');
 const calc=context?.calc||new Calc(doc),rows=[];for(let r=a.r;r<=b.r;r++){const row=[];for(let c=a.c;c<=b.c;c++){const value=calc.value(si,r,c);if(isErr(value))throw Error(`${A(r,c)}: ${value.err}`);row.push(value);}rows.push(row);}
 return check({columns:rows.shift().map(String),rows});
}
function aggregate(values,fn) {const numbers=values.filter(v=>typeof v==='number'&&Number.isFinite(v));if(fn==='count')return values.filter(v=>!blank(v)).length;if(fn==='countRows')return values.length;if(fn==='distinct')return new Set(values.map(v=>JSON.stringify(v))).size;if(!numbers.length)return null;return fn==='average'?numbers.reduce((a,b)=>a+b,0)/numbers.length:fn==='min'?numbers.reduce((a,b)=>Math.min(a,b),Infinity):fn==='max'?numbers.reduce((a,b)=>Math.max(a,b),-Infinity):numbers.reduce((a,b)=>a+b,0);}
export function transformQuery(input,step,resolve) {
 let data=check(input),rows=data.rows,columns=data.columns;const col=()=>index(data,step.column),fields=step.columns||[step.column];
 switch(step.type) {
 case 'select':return project(data,fields);
 case 'remove':return project(data,columns.filter(c=>!fields.includes(c)));
 case 'rename': {const i=col();columns=columns.slice();columns[i]=step.name;break;}
 case 'filter': {const i=col(),v=step.value,compare=(x)=>{const n=typeof x==='number'?Number(v):String(v??''),t=String(x??'');switch(step.op){case 'ne':return x!==n;case 'gt':return x>n;case 'ge':return x>=n;case 'lt':return x<n;case 'le':return x<=n;case 'contains':return t.includes(String(v));case 'starts':return t.startsWith(String(v));case 'blank':return blank(x);case 'notBlank':return !blank(x);default:return x===n;}};rows=rows.filter(r=>compare(r[i]));break;}
 case 'sort': {const keys=(step.keys||[{column:step.column,descending:step.descending}]).map(k=>({...k,index:index(data,k.column)}));rows=rows.slice().sort((a,b)=>{for(const k of keys){const x=a[k.index],y=b[k.index];const c=blank(x)?blank(y)?0:1:blank(y)?-1:typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true});if(c)return c*(k.descending?-1:1);}return 0;});break;}
 case 'distinct': {const ids=fields.filter(Boolean).length?fields.map(c=>index(data,c)):columns.map((_,i)=>i),seen=new Set();rows=rows.filter(r=>{const k=JSON.stringify(ids.map(i=>r[i]));if(seen.has(k))return false;seen.add(k);return true;});break;}
 case 'replace':case 'trim':case 'type':case 'fillDown': {const ids=fields.map(c=>index(data,c)),last=new Map();rows=rows.map(r=>{r=r.slice();for(const i of ids){let v=r[i];if(step.type==='replace'){if(step.substring)v=String(v??'').split(String(step.from)).join(String(step.to));else if(String(v??'')===String(step.from))v=step.to;}else if(step.type==='trim')v=typeof v==='string'?v.trim():v;else if(step.type==='fillDown'){if(blank(v)&&last.has(i))v=last.get(i);else if(!blank(v))last.set(i,v);}else if(!blank(v)){if(step.as==='number'){v=Number(v);if(!Number.isFinite(v))throw Error('无法转换为数字：'+r[i]);}else if(step.as==='boolean'){if(!/^(true|false|1|0)$/i.test(String(v)))throw Error('无法转换为布尔值：'+v);v=/^(true|1)$/i.test(String(v));}else if(step.as==='date'){const d=new Date(v);if(!Number.isFinite(+d))throw Error('无法转换为日期：'+v);v=d.toISOString().slice(0,10);}else v=String(v);}r[i]=v;}return r;});break;}
 case 'split': {const i=col(),parts=rows.map(r=>String(r[i]??'').split(step.delimiter??',')),n=parts.reduce((n,p)=>Math.max(n,p.length),1);columns=columns.filter((_,j)=>j!==i);const names=Array.from({length:n},(_,j)=>step.names?.[j]||step.column+'.'+(j+1));columns.splice(i,0,...names);rows=rows.map((r,k)=>[...r.slice(0,i),...names.map((_,j)=>parts[k][j]??''),...r.slice(i+1)]);break;}
 case 'addColumn': {const prepared=String(step.formula||'').replace(/"(?:""|[^"])*"|\[([^\]]+)\]/g,(text,name)=>name===undefined?text:A(0,index(data,name))),work={sheets:[{name:'Query',cells:{}}]};columns=[...columns,step.name];rows=rows.map(r=>{work.sheets[0].cells=Object.fromEntries(r.map((v,c)=>[A(0,c),{v,literal:typeof v==='string'&&v.startsWith('=')}]));work.sheets[0].cells[A(0,r.length)]={v:'='+prepared.replace(/^=/,'')};const v=new Calc(work).value(0,0,r.length);if(isErr(v))throw Error('计算列：'+v.err);return [...r,v];});break;}
 case 'group': {const ids=fields.map(c=>index(data,c)),stats=step.values||[{column:step.valueColumn,fn:step.fn||'sum',name:step.name||'汇总'}],groups=new Map();for(const r of rows){const key=JSON.stringify(ids.map(i=>r[i]));if(!groups.has(key))groups.set(key,{keys:ids.map(i=>r[i]),rows:[]});groups.get(key).rows.push(r);}columns=[...fields,...stats.map(s=>s.name||s.fn+' '+s.column)];rows=[...groups.values()].map(g=>[...g.keys,...stats.map(s=>aggregate(g.rows.map(r=>r[index(data,s.column)]),s.fn))]);break;}
 case 'append': {const other=resolve(step.source),all=[...new Set([...columns,...other.columns])];rows=[...rows.map(r=>all.map(c=>columns.includes(c)?r[columns.indexOf(c)]:null)),...other.rows.map(r=>all.map(c=>other.columns.includes(c)?r[other.columns.indexOf(c)]:null))];columns=all;break;}
 case 'merge': {const other=resolve(step.source),left=(step.left||fields).map(c=>index(data,c)),right=(step.right||fields).map(c=>index(other,c));if(left.length!==right.length)throw Error('两侧连接键数量必须相同');const lookup=new Map(),seen=new Set();other.rows.forEach((r,i)=>{const key=JSON.stringify(right.map(j=>r[j]));if(!lookup.has(key))lookup.set(key,[]);lookup.get(key).push([r,i]);});const names=other.columns.map(c=>columns.includes(c)?(step.prefix||'合并')+'.'+c:c);const out=[];for(const r of rows){const hits=lookup.get(JSON.stringify(left.map(j=>r[j])))||[];if(step.join==='anti'){if(!hits.length)out.push(r);continue;}if(step.join==='semi'){if(hits.length)out.push(r);continue;}if(!hits.length&&step.join!=='inner')out.push([...r,...other.columns.map(()=>null)]);for(const [rr,i] of hits){if(out.length>=1048575)throw Error('连接结果超过工作表上限');out.push([...r,...rr]);seen.add(i);}if(out.length>1048575)throw Error('连接结果超过工作表上限');}if(step.join==='full')other.rows.forEach((r,i)=>{if(!seen.has(i)){if(out.length>=1048575)throw Error('连接结果超过工作表上限');out.push([...columns.map(()=>null),...r]);}});rows=out;if(!['anti','semi'].includes(step.join))columns=[...columns,...names];break;}
 case 'unpivot': {const ids=fields.map(c=>index(data,c)),keep=columns.map((_,i)=>i).filter(i=>!ids.includes(i));if(rows.length*ids.length>1048575)throw Error('逆透视结果超过工作表上限');rows=rows.flatMap(r=>ids.map(i=>[...keep.map(j=>r[j]),columns[i],r[i]]));columns=[...keep.map(i=>columns[i]),step.attribute||'属性',step.valueName||'值'];break;}
 case 'pivot': {const field=col(),vi=index(data,step.valueColumn),keep=columns.map((_,i)=>i).filter(i=>i!==field&&i!==vi),names=[...new Set(rows.map(r=>String(r[field])))],groups=new Map();for(const r of rows){const key=JSON.stringify(keep.map(i=>r[i]));if(!groups.has(key))groups.set(key,{keys:keep.map(i=>r[i]),data:new Map()});const m=groups.get(key).data,n=String(r[field]);if(!m.has(n))m.set(n,[]);m.get(n).push(r[vi]);}columns=[...keep.map(i=>columns[i]),...names];rows=[...groups.values()].map(g=>[...g.keys,...names.map(n=>aggregate(g.data.get(n)||[],step.fn||'sum'))]);break;}
 case 'take':rows=rows.slice(Math.max(0,+step.skip||0),Math.max(0,+step.skip||0)+Math.max(0,+step.count||0));break;
 default:throw Error('未知查询步骤：'+step.type);
 }
 return check({columns,rows});
}
export function runQuery(doc,name,context={cache:new Map(),stack:new Set(),calc:new Calc(doc)}) {
 if(context.cache.has(name))return context.cache.get(name);if(context.stack.has(name))throw Error('查询存在循环依赖：'+name);
 const q=doc.queries?.find(q=>same(q.name,name));if(!q)throw Error('找不到查询：'+name);context.stack.add(name);
 try{let data=querySource(doc,q.source,context);for(const step of q.steps||[])data=transformQuery(data,step,source=>querySource(doc,source,context));context.cache.set(name,data);return data;}finally{context.stack.delete(name);}
}
export function loadQueryResult(doc,query,data) {
 check(data);if(!query.targetSheet||query.targetSheet.length>31||/[\[\]:*?\/\\]/.test(query.targetSheet))throw Error('结果工作表名称无效');let sh=doc.sheets.find(s=>same(s.name,query.targetSheet));if(!sh){sh={name:query.targetSheet,cells:{}};doc.sheets.push(sh);sh=doc.sheets[doc.sheets.length-1];}if(sh.protected)throw Error('查询目标工作表已保护');
 const a=parseA(query.target||'A1');if(!a||a.r+data.rows.length>=1048576||a.c+data.columns.length>16384)throw Error('查询结果超过工作表上限');
 const inside=(p,range)=>{if(!range)return false;const [x,y0]=range.split(':').map(parseA),y=y0||x;return x&&y&&p.r>=x.r&&p.r<=y.r&&p.c>=x.c&&p.c<=y.c;},range=A(a.r,a.c)+':'+A(a.r+data.rows.length,a.c+data.columns.length-1);
 const overlaps=other=>{if(!other)return false;const [x,y0]=other.split(':').map(parseA),y=y0||x;return x&&y&&x.r<=a.r+data.rows.length&&y.r>=a.r&&x.c<a.c+data.columns.length&&y.c>=a.c;};
 const sources=[query.source,...(query.steps||[]).map(s=>s.source).filter(Boolean)];
 if(sources.some(source=>same(source.sheet,sh.name)&&overlaps(source.range)||(sh.tables||[]).some(t=>same(t.name,source.table)&&overlaps(t.range))))throw Error('查询结果不能覆盖其数据源');
 if((doc.queries||[]).some(q=>q.name!==query.name&&same(q.targetSheet,sh.name)&&overlaps(q.range)))throw Error('查询结果与其他查询重叠');
 for(const [ref,cell] of Object.entries(sh.cells)){const p=parseA(ref);if(inside(p,range)&&!inside(p,query.range)&&!blank(cell.v))throw Error('查询结果会覆盖已有单元格：'+ref);}
 if((sh.merges||[]).some(m=>m.r<=a.r+data.rows.length&&m.r+m.rs>a.r&&m.c<a.c+data.columns.length&&m.c+m.cs>a.c))throw Error('查询结果不能覆盖合并单元格');
 for(const ref of Object.keys(sh.cells))if(inside(parseA(ref),query.range)){const s=sh.cells[ref].s;if(s)sh.cells[ref]={v:'',s};else delete sh.cells[ref];}
 [data.columns,...data.rows].forEach((row,r)=>row.forEach((value,c)=>{const ref=A(a.r+r,a.c+c),old=sh.cells[ref];sh.cells[ref]={v:value??'',...(typeof value==='string'&&value.startsWith('=')?{literal:true}:{}),s:old?.s||(r?{}:{b:true,fill:'#E8EEF7'})};}));query.range=range;return sh;
}
export function refreshQueries(doc,names=doc.queries?.map(q=>q.name)||[]) {const context={cache:new Map(),stack:new Set(),calc:new Calc(doc)},output=names.map(name=>[doc.queries.find(q=>same(q.name,name)),runQuery(doc,name,context)]);for(const [q,data] of output)loadQueryResult(doc,q,data);return output.map(([q,d])=>({name:q.name,rows:d.rows.length,columns:d.columns.length}));}
